import Image from 'next/image';
import Head from 'next/head';
import Link from 'next/link';

//components
import Footer from '../../layout/footer';
import NavBar from '../../layout/navbar';

//data
import services from '../../data/services.json';

//css
import styles from '../../styles/Service.module.css';

export default function Servicio({name,service}){

    const data = JSON.parse(service);

    return(
        <div id={styles.service}>
            <Head>
                <title>{name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <section className={styles.container}>
            
                <h6 className={styles.title} id="title">{data.title}</h6>
            
                <div className={styles.data}>
                    <div className={styles.image}>
                        <Image src={data.link} alt={data.alt} width={100} height={60} layout="responsive" />
                    </div>
                    <div className={styles.text}>
                        <p className={styles.desc}>
                            {data.desc}
                        </p>

                        {
                        data.details
                        &&
                        <div className={styles.details}>
                            <span className={styles.detailsTitle}>Detalles</span>

                            
                            
                            {
                                data.details.map((d,i)=><span key={i} className={styles.detail}> {d.name}: {d.data}  </span>)
                            }

                            

                        </div>
                        }

                        <Link href={{pathname:"/contacto",query:{service:data.title}}}><a className={styles.contact}>Contactanos</a></Link>
                    
                    </div>

                </div>

                
                
                

            </section>

            <Footer />

        </div>
        
    )

}

export async function getStaticPaths(){
    //config Services
    const pathsTel = services.ServicesTelec.map(s=>{return{params:{name:[s.title,"telecomunicaciones"]}}})
    const pathsCons = services.ServicesConst.map(s=>{return{params:{name:[s.title,"construccion"]}}});
    const pathsMud = services.ServicesMud.map(s=>{return{params:{name:[s.title,"mudanza"]}}})

    const paths = [...pathsCons,...pathsTel,...pathsMud];
    
    return{
        paths,
        fallback: false 
    }
}

export async function getStaticProps({params}){
    let service;

    if(params.name[1]=== "construccion"){
        service = services.ServicesConst.find(e => e.title===params.name[0]);
    }

    if(params.name[1] === "telecomunicaciones"){
        service = services.ServicesTelec.find(e => e.title===params.name[0]);
    }

    if(params.name[1] === "mudanza"){
        service = services.ServicesMud.find(e => e.title===params.name[0]);
    }

    return {
      props:{
        name:params.name[0],
        service:JSON.stringify(service)
      }
    }
  }
  