import Head from 'next/head'

//components
import Footer from '../../layout/footer';
import Navbar from '../../layout/navbar'
import ViewService from '../../components/services/viewService';

//css
import styles from '../../styles/Services.module.css'

//data services
import services from '../../data/services';


export default function Home({telecom,construccion,mudanza}) {
  
  return (
    <div id={styles.body}>
      
      <Head>
        <title>Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>

      <main className={styles.serviciosContainer}>
        

        <section className={styles.services}>
          <h4 className={styles.subtitle}>Construccion</h4>
          
          {
            (construccion && construccion.length)
            &&
            construccion.map((service,key)=><ViewService key={key} type="construccion" {...service} />)
          }
          
        </section>

        <section className={styles.services}>
          <h4 className={styles.subtitle}>TeleComunicaciones</h4>

          {
            (telecom && telecom.length)
            &&
            telecom.map((service,key)=><ViewService key={key} type="telecomunicaciones" {...service} />)
          }

        </section>

        <section className={styles.services}>

          <h4 className={styles.subtitle}>Mudanzas</h4>

          {
            (mudanza && mudanza.length)
            &&
            mudanza.map((service,key)=><ViewService key={key} type="mudanza" {...service} />)
          }

        </section>

        <Footer/>
        
      </main>
      
    </div>
  )
}

export async function getStaticProps(){
  return {
    props:{
      telecom:services.ServicesTelec,
      construccion:services.ServicesConst,
      mudanza:services.ServicesMud    
    }
  }
}
